# Generated by Django 2.2.4 on 2019-09-20 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icones', '0001_initial'),
        ('lupa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icones.Icone', verbose_name='ícone'),
        ),
    ]
