# Generated by Django 2.2.2 on 2019-07-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='data_type',
            field=models.CharField(choices=[('texto_grande', 'Texto em coluna dupla'), ('texto_pequeno', 'Texto em coluna simples'), ('texto_pequeno_destaque', 'Texto destacado em coluna simples'), ('lista_sem_ordenacao', 'Lista sem ordenação'), ('lista_ordenada', 'Lista ordenada'), ('grafico_barra_vertical', 'Gráfico de barras verticais'), ('grafico_barra_horizontal', 'Gráfico de barras horizontais'), ('grafico_pizza', 'Gráfico de pizza')], default='texto_grande', max_length=50),
        ),
    ]
