# Generated by Django 2.2.4 on 2019-08-21 13:26

from django.db import migrations


def bootstrap_data_type(apps, schema_editor):
    TipoDado = apps.get_model('lupa', 'TipoDado')
    TipoDado(name='texto_grande', serialization='Singleton').save()
    TipoDado(name='texto_pequeno', serialization='Singleton').save()
    TipoDado(name='texto_pequeno_destaque', serialization='Singleton').save()
    TipoDado(name='lista_sem_ordenacao', serialization='List').save()
    TipoDado(name='lista_ordenada', serialization='List').save()
    TipoDado(name='lista_filtrada', serialization='List').save()
    TipoDado(name='lista_pessoa', serialization='List').save()
    TipoDado(name='grafico_barra_vertical', serialization='Graph').save()
    TipoDado(name='grafico_barra_horizontal', serialization='Graph').save()
    TipoDado(name='grafico_barra_horizontal_agrupado', serialization='Graph').save()
    TipoDado(name='grafico_linha_horizontal', serialization='Graph').save()
    TipoDado(name='grafico_pizza', serialization='Graph').save()


def move_data_type(apps, schema_editor):
    Dado = apps.get_model('lupa', 'Dado')
    TipoDado = apps.get_model('lupa', 'TipoDado')

    for dado in Dado.objects.all():
        data_type_update = TipoDado.objects.get(name=dado.data_type_old)
        dado.data_type_new = data_type_update
        dado.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(bootstrap_data_type),
        migrations.RunPython(move_data_type),
    ]
