# Generated by Django 2.2.4 on 2019-09-04 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0002_auto_20190821_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome do grupo')),
                ('role', models.CharField(max_length=100, verbose_name='role no SCA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'grupo de usuários',
                'verbose_name_plural': 'grupos de usuários',
            },
        ),
        migrations.AlterField(
            model_name='dado',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_by_theme', to='lupa.TemaDado', verbose_name='tema da caixinha'),
        ),
        migrations.AddField(
            model_name='dado',
            name='roles_allowed',
            field=models.ManyToManyField(related_name='data_allowed', to='lupa.Grupo', verbose_name='usuários com permissão'),
        ),
    ]
