# Generated by Django 2.2.4 on 2019-09-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0003_auto_20190906_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome do grupo')),
                ('role', models.CharField(max_length=100, verbose_name='role no SCA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'grupo de usuários',
                'verbose_name_plural': 'grupos de usuários',
            },
        ),
        migrations.AddField(
            model_name='dado',
            name='roles_allowed',
            field=models.ManyToManyField(blank=True, help_text='Deixar em branco para todos', related_name='data_allowed', to='lupa.Grupo', verbose_name='grupos com acesso'),
        ),
    ]
