# Generated by Django 2.2.2 on 2019-10-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0003_dado_show_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='is_cacheable',
            field=models.BooleanField(default=True, verbose_name='guardar no cache?'),
        ),
    ]
