# Generated by Django 2.2.4 on 2019-09-09 18:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0003_auto_20190906_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temadado',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18, verbose_name='cor das caixinhas'),
        ),
    ]
