# Generated by Django 2.2.4 on 2019-10-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icones', '0001_initial'),
        ('lupa', '0003_dado_show_box'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dado',
            new_name='DadoEntidade',
        ),
    ]
