# Generated by Django 2.2.4 on 2019-10-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0004_auto_20191016_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadoentidade',
            options={},
        ),
    ]
