# Generated by Django 2.2.2 on 2019-10-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0004_entidade_is_cacheable'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='is_cacheable',
            field=models.BooleanField(default=True, verbose_name='guardar no cache?'),
        ),
    ]
