# Generated by Django 2.2.4 on 2019-09-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0004_auto_20190906_1947'),
        ('lupa', '0004_auto_20190909_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='roles_allowed',
            field=models.ManyToManyField(blank=True, help_text='Deixar em branco para todos', related_name='entity_allowed', to='lupa.Grupo', verbose_name='grupos com acesso'),
        ),
    ]
