# Generated by Django 2.2.5 on 2019-09-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0005_entidade_roles_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='geojson_column',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='coluna de dados geojson da entidade'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='osm_default_level',
            field=models.BooleanField(default=False, verbose_name='busca de geolocalização padrão'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='osm_value_attached',
            field=models.CharField(blank=True, choices=[('suburb', 'Bairro'), ('municipality', 'Município')], max_length=50, null=True, verbose_name='osm_values atrelados'),
        ),
    ]
