# Generated by Django 2.2.4 on 2019-10-16 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icones', '0001_initial'),
        ('lupa', '0005_auto_20191016_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadoentidade',
            options={'verbose_name': 'dado'},
        ),
        migrations.AlterField(
            model_name='dadoentidade',
            name='show_box',
            field=models.BooleanField(default=True, verbose_name='exibir dado'),
        ),
        migrations.CreateModel(
            name='DadoDetalhe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(max_length=100, verbose_name='titulo da caixinha')),
                ('exibition_field', models.CharField(blank=True, help_text='Não obrigatório', max_length=100, null=True, verbose_name='nome de exibição da caixinha')),
                ('database', models.CharField(choices=[('PG', 'PostgreSQL Opengeo'), ('ORA', 'Oracle ExaData'), ('BDA', 'Oracle BDA')], default='PG', max_length=3, verbose_name='banco de dados')),
                ('schema', models.CharField(max_length=100, verbose_name='esquema')),
                ('table', models.CharField(max_length=100, verbose_name='tabela')),
                ('limit_fetch', models.IntegerField(default=0, help_text='0 = sem limite', verbose_name='máximo de dados a serem mostrados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('dado_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_details', to='lupa.DadoEntidade', verbose_name='detalhes')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details_by_type', to='lupa.TipoDado', verbose_name='tipo do detalhe')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icones.Icone', verbose_name='ícone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
