# Generated by Django 2.2.2 on 2019-10-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0005_dado_is_cacheable'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='cache_timeout',
            field=models.BigIntegerField(default=7, verbose_name='Tempo de persistência do cache (em dias)'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='cache_timeout',
            field=models.BigIntegerField(default=7, verbose_name='Tempo de persistência do cache (em dias)'),
        ),
    ]
