# Generated by Django 2.2.2 on 2019-07-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0005_auto_20190725_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dado',
            old_name='external_link_column',
            new_name='external_link_id_column',
        ),
    ]
