# Generated by Django 2.2.2 on 2019-10-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0006_auto_20191018_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='last_cache_update',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='entidade',
            name='last_cache_update',
            field=models.DateField(null=True),
        ),
    ]
