# Generated by Django 2.2.4 on 2019-09-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0006_auto_20190912_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='geojson_column',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='coluna de dados GEOJSON da entidade'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='osm_value_attached',
            field=models.CharField(blank=True, choices=[('suburb', 'Bairro'), ('municipality', 'Município')], max_length=50, null=True, verbose_name='TAG osm_values atrelada'),
        ),
    ]
