# Generated by Django 2.2.4 on 2019-10-18 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0007_auto_20191016_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColunaDetalhe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome da coluna na tabela')),
                ('info_type', models.CharField(default='id', max_length=50, verbose_name='tipo de informação da coluna')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('dado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_list', to='lupa.DadoDetalhe', verbose_name='dado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
