# Generated by Django 2.2.2 on 2019-10-24 17:34

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0008_colunadetalhe'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dadodetalhe',
            managers=[
                ('cache', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dadoentidade',
            managers=[
                ('cache', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='dadodetalhe',
            name='cache_timeout',
            field=models.BigIntegerField(default=7, verbose_name='Tempo de persistência do cache (em dias)'),
        ),
        migrations.AddField(
            model_name='dadodetalhe',
            name='is_cacheable',
            field=models.BooleanField(default=True, verbose_name='guardar no cache?'),
        ),
        migrations.AddField(
            model_name='dadodetalhe',
            name='last_cache_update',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dadodetalhe',
            name='show_box',
            field=models.BooleanField(default=True, verbose_name='Exibir dado'),
        ),
        migrations.AddField(
            model_name='dadoentidade',
            name='cache_timeout',
            field=models.BigIntegerField(default=7, verbose_name='Tempo de persistência do cache (em dias)'),
        ),
        migrations.AddField(
            model_name='dadoentidade',
            name='is_cacheable',
            field=models.BooleanField(default=True, verbose_name='guardar no cache?'),
        ),
        migrations.AddField(
            model_name='dadoentidade',
            name='last_cache_update',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='entidade',
            name='cache_timeout',
            field=models.BigIntegerField(default=7, verbose_name='Tempo de persistência do cache (em dias)'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='is_cacheable',
            field=models.BooleanField(default=True, verbose_name='guardar no cache?'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='last_cache_update',
            field=models.DateField(null=True),
        ),
    ]
