# Generated by Django 2.2.2 on 2019-07-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0008_auto_20190725_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dado',
            old_name='entity_link_column',
            new_name='entity_link_id_column',
        ),
    ]
