# Generated by Django 2.2.2 on 2019-10-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0009_auto_20191024_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadodetalhe',
            name='cache_timeout',
        ),
        migrations.RemoveField(
            model_name='dadoentidade',
            name='cache_timeout',
        ),
        migrations.RemoveField(
            model_name='entidade',
            name='cache_timeout',
        ),
        migrations.AddField(
            model_name='dadodetalhe',
            name='cache_timeout_days',
            field=models.IntegerField(default=7, verbose_name='Tempo de persistência do cache (em dias)'),
        ),
        migrations.AddField(
            model_name='dadodetalhe',
            name='cache_timeout_sec',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dadoentidade',
            name='cache_timeout_days',
            field=models.IntegerField(default=7, verbose_name='Tempo de persistência do cache (em dias)'),
        ),
        migrations.AddField(
            model_name='dadoentidade',
            name='cache_timeout_sec',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entidade',
            name='cache_timeout_days',
            field=models.IntegerField(default=7, verbose_name='Tempo de persistência do cache (em dias)'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='cache_timeout_sec',
            field=models.BigIntegerField(null=True),
        ),
    ]
