# Generated by Django 2.2.4 on 2019-11-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0010_auto_20191029_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoentidade',
            name='roles_allowed',
            field=models.ManyToManyField(blank=True, help_text='Deixar em branco para todos\nUsar "Usuários autorizados" para qualquer usuário logado\nUsar "Convidados" para qualquer usuário NÃO logado', related_name='data_allowed', to='lupa.Grupo', verbose_name='grupos com acesso'),
        ),
    ]
