# Generated by Django 2.2.2 on 2019-07-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0010_auto_20190725_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='database_mapa',
            field=models.CharField(choices=[('PG', 'PostgreSQL Opengeo'), ('ORA', 'Oracle ExaData'), ('BDA', 'Oracle BDA')], default='PG', max_length=3),
        ),
    ]
