# Generated by Django 2.2.2 on 2019-11-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0010_auto_20191029_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadodetalhe',
            name='last_cache_update',
            field=models.DateField(blank=True, null=True, verbose_name='Data da última atualização do cache'),
        ),
        migrations.AlterField(
            model_name='dadoentidade',
            name='last_cache_update',
            field=models.DateField(blank=True, null=True, verbose_name='Data da última atualização do cache'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='last_cache_update',
            field=models.DateField(blank=True, null=True, verbose_name='Data da última atualização do cache'),
        ),
    ]
