# Generated by Django 2.2.2 on 2019-07-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0011_entidade_database_mapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='entity_link_id_column',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entidade',
            name='entity_link_type',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
