# Generated by Django 2.2.4 on 2019-11-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0011_auto_20191111_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoentidade',
            name='roles_allowed',
            field=models.ManyToManyField(blank=True, help_text='Deixar em branco para todos<br>Usar "Usuários autorizados" para qualquer usuário logado<br>Usar "Convidados" para qualquer usuário NÃO logado<br>', related_name='data_allowed', to='lupa.Grupo', verbose_name='grupos com acesso'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='roles_allowed',
            field=models.ManyToManyField(blank=True, help_text='Deixar em branco para todos<br>Usar "Usuários autorizados" para qualquer usuário logado<br>Usar "Convidados" para qualquer usuário NÃO logado<br>', related_name='entity_allowed', to='lupa.Grupo', verbose_name='grupos com acesso'),
        ),
    ]
