# Generated by Django 2.2.4 on 2019-11-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0012_auto_20191111_1900'),
        ('lupa', '0011_auto_20191107_1249'),
    ]

    operations = [
    ]
