# Generated by Django 2.2.4 on 2019-11-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0013_merge_20191119_1915'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dadodetalhe',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='dadoentidade',
            managers=[
            ],
        ),
    ]
