# Generated by Django 2.2.2 on 2019-07-26 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0013_auto_20190725_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='map_info', serialize=False, to='lupa.Entidade')),
                ('database', models.CharField(choices=[('PG', 'PostgreSQL Opengeo'), ('ORA', 'Oracle ExaData'), ('BDA', 'Oracle BDA')], default='PG', max_length=3)),
                ('schema', models.CharField(max_length=50)),
                ('table', models.CharField(max_length=50)),
                ('entity_id_column', models.CharField(max_length=50)),
                ('label_column', models.CharField(max_length=50)),
                ('geom_column', models.CharField(max_length=50)),
                ('related_entity_column', models.CharField(max_length=50)),
                ('related_id_column', models.CharField(max_length=50)),
            ],
        ),
    ]
