# Generated by Django 2.2.2 on 2019-08-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0018_auto_20190802_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='data_type',
            field=models.CharField(choices=[('texto_grande', 'Texto em coluna dupla'), ('texto_pequeno', 'Texto em coluna simples'), ('texto_pequeno_destaque', 'Texto destacado em coluna simples'), ('lista_sem_ordenacao', 'Lista sem ordenação'), ('lista_ordenada', 'Lista ordenada'), ('lista_filtrada', 'Lista sem ordenação com filtro de busca'), ('lista_pessoa', 'Lista de pessoas'), ('grafico_barra_vertical', 'Gráfico de barras verticais'), ('grafico_barra_horizontal', 'Gráfico de barras horizontais'), ('grafico_barra_horizontal_agrupado', 'Gráfico de barras horizontais agrupadas'), ('grafico_linha_horizontal', 'Gráfico de linha horizontal'), ('grafico_pizza', 'Gráfico de pizza')], default='texto_grande', max_length=50),
        ),
    ]
