# Generated by Django 2.2.2 on 2019-08-02 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0019_auto_20190802_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dado',
            name='exibition_field',
        ),
        migrations.AlterField(
            model_name='dado',
            name='data_column',
            field=models.CharField(max_length=200, verbose_name='Coluna da informação principal exibida'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='data_type',
            field=models.CharField(choices=[('texto_grande', 'Texto em coluna dupla'), ('texto_pequeno', 'Texto em coluna simples'), ('texto_pequeno_destaque', 'Texto destacado em coluna simples'), ('lista_sem_ordenacao', 'Lista sem ordenação'), ('lista_ordenada', 'Lista ordenada'), ('lista_filtrada', 'Lista sem ordenação com filtro de busca'), ('lista_pessoa', 'Lista de pessoas'), ('grafico_barra_vertical', 'Gráfico de barras verticais'), ('grafico_barra_horizontal', 'Gráfico de barras horizontais'), ('grafico_barra_horizontal_agrupado', 'Gráfico de barras horizontais agrupadas'), ('grafico_linha_horizontal', 'Gráfico de linha horizontal'), ('grafico_pizza', 'Gráfico de pizza')], default='texto_grande', max_length=50, verbose_name='Tipo de caixinha'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='database',
            field=models.CharField(choices=[('PG', 'PostgreSQL Opengeo'), ('ORA', 'Oracle ExaData'), ('BDA', 'Oracle BDA')], default='PG', max_length=3, verbose_name='Banco de dados'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='details_column',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Coluna de detalhes sobre os dados'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='entity_link_id_column',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Coluna de ID da entidade apontada'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='entity_link_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lupa.Entidade', verbose_name='Entidade apontada em link interno'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_list', to='lupa.Entidade', verbose_name='Entidade relacionada'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='external_link_column',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Coluna de link externo'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lupa.Icone', verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='id_column',
            field=models.CharField(max_length=200, verbose_name='Coluna do ID da Entidade'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='image_column',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Coluna de imagem'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='label_column',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Coluna de rótulo dos dados'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='schema',
            field=models.CharField(max_length=100, verbose_name='Esquema'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='source_column',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Coluna de fonte dos dados'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='table',
            field=models.CharField(max_length=100, verbose_name='Tabela'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titulo da caixinha'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='abreviation',
            field=models.CharField(max_length=5, verbose_name='Abreviação da entidade'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='database',
            field=models.CharField(choices=[('PG', 'PostgreSQL Opengeo'), ('ORA', 'Oracle ExaData'), ('BDA', 'Oracle BDA')], default='PG', max_length=3, verbose_name='Banco de dados'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='id_column',
            field=models.CharField(max_length=200, verbose_name='Coluna de ID da entidade'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Nome da entidade'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='name_column',
            field=models.CharField(max_length=200, verbose_name='Coluna de nome da entidade'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='schema',
            field=models.CharField(max_length=100, verbose_name='Esquema'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='table',
            field=models.CharField(max_length=100, verbose_name='Tabela'),
        ),
        migrations.AlterField(
            model_name='icone',
            name='file_path',
            field=models.FileField(upload_to='icones', verbose_name='Arquivo do ícone'),
        ),
        migrations.AlterField(
            model_name='icone',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Título do ícone'),
        ),
    ]
