# Generated by Django 2.2.2 on 2019-08-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0024_auto_20190808_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='data_type_new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_type', to='lupa.TipoDado', verbose_name='Tipo da caixinha'),
        ),
    ]
