# Generated by Django 2.2.2 on 2019-08-09 23:06

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0029_auto_20190809_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='exibition_field',
            field=models.CharField(blank=True, help_text='Não obrigatório', max_length=100, null=True, verbose_name='nome de exibição da caixinha'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='data_column',
            field=models.CharField(max_length=200, verbose_name='coluna da informação principal exibida'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_type', to='lupa.TipoDado', verbose_name='tipo da caixinha'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='database',
            field=models.CharField(choices=[('PG', 'PostgreSQL Opengeo'), ('ORA', 'Oracle ExaData'), ('BDA', 'Oracle BDA')], default='PG', max_length=3, verbose_name='banco de dados'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='details_column',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='coluna de detalhes sobre os dados'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='entity_link_id_column',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='coluna de ID da entidade apontada'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='entity_link_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lupa.Entidade', verbose_name='entidade apontada em link interno'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_list', to='lupa.Entidade', verbose_name='entidade relacionada'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='external_link_column',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='coluna de link externo'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lupa.Icone', verbose_name='ícone'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='id_column',
            field=models.CharField(max_length=200, verbose_name='coluna do ID da Entidade'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='image_column',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='coluna de imagem'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='label_column',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='coluna de rótulo dos dados'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='limit_fetch',
            field=models.IntegerField(default=0, help_text='0 = sem limite', verbose_name='máximo de dados a serem mostrados'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='schema',
            field=models.CharField(max_length=100, verbose_name='esquema'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='source_column',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='coluna de fonte dos dados'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='table',
            field=models.CharField(max_length=100, verbose_name='tabela'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_by_theme', to='lupa.TemaDado', verbose_name='tema da caixinha'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='title',
            field=models.CharField(max_length=100, verbose_name='titulo da caixinha'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='abreviation',
            field=models.CharField(max_length=5, verbose_name='abreviação da entidade'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='database',
            field=models.CharField(choices=[('PG', 'PostgreSQL Opengeo'), ('ORA', 'Oracle ExaData'), ('BDA', 'Oracle BDA')], default='PG', max_length=3, verbose_name='banco de dados'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='id_column',
            field=models.CharField(max_length=200, verbose_name='coluna de ID da entidade'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='name',
            field=models.CharField(max_length=25, verbose_name='nome da entidade'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='name_column',
            field=models.CharField(max_length=200, verbose_name='coluna de nome da entidade'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='schema',
            field=models.CharField(max_length=100, verbose_name='esquema'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='table',
            field=models.CharField(max_length=100, verbose_name='tabela'),
        ),
        migrations.AlterField(
            model_name='icone',
            name='file_path',
            field=models.FileField(upload_to='icones', verbose_name='arquivo do ícone'),
        ),
        migrations.AlterField(
            model_name='icone',
            name='name',
            field=models.CharField(max_length=20, verbose_name='título do ícone'),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='database',
            field=models.CharField(choices=[('PG', 'PostgreSQL Opengeo'), ('ORA', 'Oracle ExaData'), ('BDA', 'Oracle BDA')], default='PG', max_length=3, verbose_name='banco de dados'),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='entity_id_column',
            field=models.CharField(max_length=50, verbose_name='coluna do ID da entidade'),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='geom_column',
            field=models.CharField(max_length=50, verbose_name='coluna do json do mapa'),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='label_column',
            field=models.CharField(max_length=50, verbose_name='coluna do label do mapa'),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='related_entity_column',
            field=models.CharField(max_length=50, verbose_name='coluna da entidade apontada'),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='related_id_column',
            field=models.CharField(max_length=50, verbose_name='coluna do ID apontado'),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='schema',
            field=models.CharField(max_length=50, verbose_name='esquema'),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='table',
            field=models.CharField(max_length=50, verbose_name='tabela'),
        ),
        migrations.AlterField(
            model_name='temadado',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='cor das caixinhas'),
        ),
        migrations.AlterField(
            model_name='temadado',
            name='name',
            field=models.CharField(max_length=50, verbose_name='tema do dado'),
        ),
        migrations.AlterField(
            model_name='tipodado',
            name='name',
            field=models.CharField(max_length=50, verbose_name='tipo de dado'),
        ),
        migrations.AlterField(
            model_name='tipodado',
            name='serialization',
            field=models.CharField(choices=[('Singleton', 'Serialização para dado único'), ('List', 'Serialização para lista de dados'), ('Graph', 'Serialização para gráfico')], default='Singleton', max_length=20, verbose_name='forma de serialização'),
        ),
    ]
