# Generated by Django 2.2.4 on 2019-08-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0031_auto_20190812_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodado',
            name='serialization',
            field=models.CharField(choices=[('Singleton', 'Serialização para dado único'), ('List', 'Serialização para lista de dados'), ('Graph', 'Serialização para gráfico cartesiano'), ('Pizza', 'Serialização para gráfico de pizza')], default='Singleton', max_length=20, verbose_name='forma de serialização'),
        ),
    ]
