# Generated by Django 2.2.4 on 2019-08-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupa', '0032_auto_20190813_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColunaDado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome da coluna na tabela')),
                ('info_type', models.CharField(default='id', help_text='<pre>Toda caixinha e mapa precisa de uma coluna de id\n        Toda caixinha precisa de uma coluna de dados\n        Todo mapa precisa de uma coluna de geojson, contendo um mapa em formato geojson\n        Caixinhas de gráficos precisam de uma coluna do tipo label\n        Colunas de imagem precisam referenciar um campo do tipo "BLOB"\n        Colunas de tipo e id de entidade vinculada precisam existir aos pares</pre>', max_length=50, verbose_name='tipo de informação da coluna')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ColunaMapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome da coluna na tabela')),
                ('info_type', models.CharField(default='id', help_text='<pre>Toda caixinha e mapa precisa de uma coluna de id\n        Toda caixinha precisa de uma coluna de dados\n        Todo mapa precisa de uma coluna de geojson, contendo um mapa em formato geojson\n        Caixinhas de gráficos precisam de uma coluna do tipo label\n        Colunas de imagem precisam referenciar um campo do tipo "BLOB"\n        Colunas de tipo e id de entidade vinculada precisam existir aos pares</pre>', max_length=50, verbose_name='tipo de informação da coluna')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dado',
            name='columns',
            field=models.ManyToManyField(to='lupa.ColunaDado'),
        ),
        migrations.AddField(
            model_name='mapa',
            name='columns',
            field=models.ManyToManyField(to='lupa.ColunaMapa'),
        ),
    ]
