language: python
addons:
  apt:
    update: true
before_install:
  - sudo apt-get install -y libgdal*
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt update -y
  - sudo apt install g++-7 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - sudo update-alternatives --config gcc
  - gcc --version
services:
  - postgresql
before_script:
  - psql -c 'create database apimpmapas;' -U postgres
python:
  - "3.7"
install:
  - pip install --upgrade pip
  - pip install -r dev-requirements.txt
script:
  - flake8 .
  - make test
notifications:
  email:
    - felipe.gomes.ferreira@gmail.com
after_success:
  - codecov