language: python
addons:
  apt:
    update: true
before_install:
  - sudo apt-get install -y libgdal*
services:
  - postgresql
before_script:
  - psql -c 'create database apimpmapas;' -U postgres
python:
  - "3.7"
install:
  - pip install --upgrade pip
  - pip install -r dev-requirements.txt
script:
  - flake8 .
  - make test
notifications:
  email:
    - felipe.gomes.ferreira@gmail.com
after_success:
  - codecov