# Generated by Django 2.2.2 on 2019-07-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('exibition_field', models.CharField(blank=True, max_length=50, null=True)),
                ('data_type', models.CharField(choices=[('NUM', 'Número'), ('TEX', 'Texto'), ('GRA', 'Gráfico')], default='TEX', max_length=3)),
                ('entity_type', models.CharField(choices=[('EST', 'Estado'), ('MUN', 'Município'), ('ORG', 'Órgão')], default='ORG', max_length=3)),
                ('database', models.CharField(choices=[('PG', 'PostgreSQL Opengeo'), ('ORA', 'Oracle ExaData'), ('BDA', 'Oracle BDA')], default='PG', max_length=3)),
                ('query', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('exibition_field', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_type', models.CharField(choices=[('EST', 'Estado'), ('MUN', 'Município'), ('ORG', 'Órgão')], default='ORG', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
