# Generated by Django 2.2.2 on 2019-07-18 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('abreviation', models.CharField(max_length=3)),
                ('database', models.CharField(choices=[('PG', 'PostgreSQL Opengeo'), ('ORA', 'Oracle ExaData'), ('BDA', 'Oracle BDA')], default='PG', max_length=3)),
                ('schema', models.CharField(max_length=100)),
                ('table', models.CharField(max_length=100)),
                ('id_column', models.CharField(max_length=200)),
                ('name_column', models.CharField(max_length=200)),
                ('geom_column', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Icone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('file_path', models.FileField(upload_to='icones')),
            ],
        ),
        migrations.CreateModel(
            name='Dado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('exibition_field', models.CharField(blank=True, max_length=50, null=True)),
                ('data_type', models.CharField(choices=[('TEX_GDE', 'Texto em coluna dupla'), ('TEX_PEQ', 'Texto em coluna simples'), ('TEX_PEQ_DEST', 'Texto destacado em coluna simples')], default='TEX_GDE', max_length=20)),
                ('database', models.CharField(choices=[('PG', 'PostgreSQL Opengeo'), ('ORA', 'Oracle ExaData'), ('BDA', 'Oracle BDA')], default='PG', max_length=3)),
                ('schema', models.CharField(max_length=100)),
                ('table', models.CharField(max_length=100)),
                ('data_column', models.CharField(max_length=200)),
                ('id_column', models.CharField(max_length=200)),
                ('source_column', models.CharField(blank=True, max_length=200, null=True)),
                ('details_column', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_list', to='api.Entidade')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Icone')),
            ],
        ),
    ]
