# Generated by Django 2.2.2 on 2019-07-04 20:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dado',
            name='query',
        ),
        migrations.AddField(
            model_name='dado',
            name='columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default='{''review''}', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dado',
            name='id_column',
            field=models.CharField(default='review', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dado',
            name='table',
            field=models.CharField(default='review', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dado',
            name='data_type',
            field=models.CharField(choices=[('NUM', 'Número'), ('TEX', 'Texto'), ('GRA', 'Gráfico'), ('MAP', 'Mapa')], default='TEX', max_length=3),
        ),
    ]
