# Generated by Django 2.2.2 on 2019-06-27 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190627_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.TipoDadoModel')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EntidadeModel')),
            ],
        ),
    ]
