# Generated by Django 2.2.2 on 2019-06-28 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dadomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('database', models.CharField(choices=[('PG', 'PostgreSQL Opengeo'), ('ORA', 'Oracle ExaData'), ('BDA', 'Oracle BDA')], default='PG', max_length=3)),
                ('query', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='EntidadeModel',
            new_name='Entidade',
        ),
        migrations.RenameModel(
            old_name='TipoDadoModel',
            new_name='TipoDado',
        ),
        migrations.RenameModel(
            old_name='TipoEntidadeModel',
            new_name='TipoEntidade',
        ),
        migrations.DeleteModel(
            name='DadoModel',
        ),
        migrations.AddField(
            model_name='dado',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.TipoDado'),
        ),
        migrations.AddField(
            model_name='dado',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TipoEntidade'),
        ),
    ]
