# Generated by Django 2.2.2 on 2019-07-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190704_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='schema',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
