# Generated by Django 2.2.2 on 2019-07-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dado_label_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='link_column',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
