# Generated by Django 2.2.2 on 2019-07-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dado_link_column'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dado',
            old_name='link_column',
            new_name='entity_link_column',
        ),
        migrations.AddField(
            model_name='dado',
            name='entity_link_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Entidade'),
        ),
        migrations.AddField(
            model_name='dado',
            name='external_link_column',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
