# Generated by Django 2.2.2 on 2019-06-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190628_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dado',
            old_name='entity',
            new_name='entity_type',
        ),
    ]
