# Generated by Django 2.2.2 on 2019-07-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190708_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='data_type',
            field=models.CharField(choices=[('TEX_GDE', 'Texto em coluna dupla'), ('TEX_PEQ', 'Texto em coluna simples'), ('TEX_PEQ_DEST', 'Texto destacado em coluna simples'), ('GRA', 'Gráfico'), ('MAP', 'Mapa')], default='TEX_GDE', max_length=20),
        ),
    ]
