# Generated by Django 2.2.2 on 2019-07-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190710_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='data_column',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dado',
            name='details_column',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dado',
            name='source_column',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
