# Generated by Django 2.2.2 on 2019-07-10 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190710_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dado',
            name='columns',
        ),
    ]
