# Generated by Django 2.2.2 on 2019-06-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dado_exibition_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='domain_id',
            field=models.CharField(default=234, max_length=20),
            preserve_default=False,
        ),
    ]
