# Generated by Django 2.2.2 on 2019-07-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190725_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dado',
            old_name='entity_link_id_column',
            new_name='external_link_column',
        ),
    ]
