# Generated by Django 2.2.2 on 2019-06-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_entidade_domain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='data_type',
            field=models.CharField(choices=[('NUM', 'Número'), ('TEX', 'Texto'), ('GRA', 'Gráfico')], default='TEX', max_length=3),
        ),
        migrations.AlterField(
            model_name='dado',
            name='entity_type',
            field=models.CharField(choices=[('EST', 'Estado'), ('MUN', 'Município'), ('ORG', 'Órgão')], default='ORG', max_length=3),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='entity_type',
            field=models.CharField(choices=[('EST', 'Estado'), ('MUN', 'Município'), ('ORG', 'Órgão')], default='ORG', max_length=3),
        ),
        migrations.DeleteModel(
            name='TipoDado',
        ),
        migrations.DeleteModel(
            name='TipoEntidade',
        ),
    ]
