# Generated by Django 2.2.2 on 2019-07-16 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_dado_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('file_path', models.FileField(upload_to='icones')),
            ],
        ),
        migrations.AlterField(
            model_name='dado',
            name='data_type',
            field=models.CharField(choices=[('TEX_GDE', 'Texto em coluna dupla'), ('TEX_PEQ', 'Texto em coluna simples'), ('TEX_PEQ_DEST', 'Texto destacado em coluna simples')], default='TEX_GDE', max_length=20),
        ),
        migrations.AddField(
            model_name='dado',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Icone'),
        ),
    ]
