# Generated by Django 2.2.2 on 2019-06-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190628_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='exibition_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
