# Generated by Django 2.2.2 on 2019-07-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190716_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='map_column_geom',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='entidade',
            name='map_column_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='entidade',
            name='map_table',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
