# Generated by Django 2.2.2 on 2019-07-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_entidade_exibition_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='geom_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
