# Generated by Django 2.2.2 on 2019-07-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190717_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEntidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('abreviation', models.CharField(max_length=3)),
                ('database', models.CharField(choices=[('PG', 'PostgreSQL Opengeo'), ('ORA', 'Oracle ExaData'), ('BDA', 'Oracle BDA')], default='PG', max_length=3)),
                ('schema', models.CharField(max_length=100)),
                ('table', models.CharField(max_length=100)),
                ('data_column', models.CharField(max_length=200)),
                ('id_column', models.CharField(max_length=200)),
                ('name_column', models.CharField(max_length=200)),
                ('geom_column', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
