# Generated by Django 2.2.2 on 2019-07-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190725_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entidade',
            old_name='geom_column',
            new_name='geom_column_mapa',
        ),
        migrations.AddField(
            model_name='entidade',
            name='id_column_mapa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entidade',
            name='name_column_mapa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entidade',
            name='schema_mapa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entidade',
            name='table_mapa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
