# Generated by Django 2.2.2 on 2019-07-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_entidade_geom_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidade',
            name='geom_file',
        ),
        migrations.RemoveField(
            model_name='entidade',
            name='geometry',
        ),
    ]
