# Generated by Django 2.2.2 on 2019-07-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tipoentidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoentidade',
            name='data_column',
        ),
    ]
