# Generated by Django 2.2.2 on 2019-07-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_tipoentidade_data_column'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entidade',
        ),
    ]
