# Generated by Django 2.2.2 on 2019-07-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190725_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='entity_link_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
