# Generated by Django 2.2.2 on 2019-07-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_entidade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoEntidade',
            new_name='Entidade',
        ),
    ]
