# Generated by Django 2.2.4 on 2019-08-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_mapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='data_type',
            field=models.CharField(choices=[('texto_grande', 'Texto em coluna dupla'), ('texto_pequeno', 'Texto em coluna simples'), ('texto_pequeno_destaque', 'Texto destacado em coluna simples'), ('lista_sem_ordenacao', 'Lista sem ordenação'), ('lista_ordenada', 'Lista ordenada'), ('lista_filtrada', 'Lista sem ordenação com filtro de busca'), ('grafico_barra_vertical', 'Gráfico de barras verticais'), ('grafico_barra_horizontal', 'Gráfico de barras horizontais'), ('grafico_barra_horizontal_agrupado', 'Gráfico de barras horizontais agrupadas'), ('grafico_pizza', 'Gráfico de pizza')], default='texto_grande', max_length=50),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='database',
            field=models.CharField(choices=[('PG', 'PostgreSQL Opengeo'), ('ORA', 'Oracle ExaData'), ('BDA', 'Oracle BDA')], default='PG', max_length=3, verbose_name='Banco de dados'),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='entity_id_column',
            field=models.CharField(max_length=50, verbose_name='Coluna do ID da entidade'),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='geom_column',
            field=models.CharField(max_length=50, verbose_name='Coluna do json do mapa'),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='label_column',
            field=models.CharField(max_length=50, verbose_name='Coluna do label do mapa'),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='related_entity_column',
            field=models.CharField(max_length=50, verbose_name='Coluna da entidade apontada'),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='related_id_column',
            field=models.CharField(max_length=50, verbose_name='Coluna do ID apontado'),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='schema',
            field=models.CharField(max_length=50, verbose_name='Esquema'),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='table',
            field=models.CharField(max_length=50, verbose_name='Tabela'),
        ),
    ]
