# Generated by Django 2.2.2 on 2019-08-01 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190801_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='entity_link_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Entidade'),
        ),
    ]
