# Generated by Django 2.2.2 on 2019-08-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190802_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='limit_fetch',
            field=models.IntegerField(default=0, help_text='0 = sem limite', verbose_name='Máximo de dados a serem mostrados'),
        ),
    ]
