# Generated by Django 2.2.2 on 2019-08-07 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190802_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Tipo de dado')),
                ('serialization', models.CharField(choices=[('Singleton', 'Serialização por dado único'), ('List', 'Serialização por lista de dados'), ('Graph', 'Serialização por gráfico')], default='Singleton', max_length=20, verbose_name='Forma de serialização')),
            ],
        ),
        migrations.RenameField(
            model_name='dado',
            old_name='data_type',
            new_name='data_type_old',
        ),
        migrations.AddField(
            model_name='dado',
            name='data_type_new',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='data_type', to='api.TipoDado', verbose_name='Tipo da caixinha'),
            preserve_default=False,
        ),
    ]
