# Generated by Django 2.2.2 on 2019-08-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_dado_limit_fetch'),
        ('api', '0020_auto_20190802_2054'),
    ]

    operations = [
    ]
