# Generated by Django 2.2.2 on 2019-08-08 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_20190808_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Tipo de dado')),
                ('serialization', models.CharField(choices=[('Singleton', 'Serialização por dado único'), ('List', 'Serialização por lista de dados'), ('Graph', 'Serialização por gráfico')], default='Singleton', max_length=20, verbose_name='Forma de serialização')),
            ],
        ),
        migrations.RenameField(
            model_name='dado',
            old_name='data_type',
            new_name='data_type_old',
        ),
        migrations.AddField(
            model_name='dado',
            name='data_type_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_type', to='api.TipoDado', verbose_name='Tipo da caixinha'),
        ),
    ]
