# Generated by Django 2.2.2 on 2019-08-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190808_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodado',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Tipo de dado'),
        ),
    ]
