# Generated by Django 2.2.2 on 2019-08-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190808_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodado',
            name='serialization',
            field=models.CharField(choices=[('Singleton', 'Serialização para dado único'), ('List', 'Serialização para lista de dados'), ('Graph', 'Serialização para gráfico')], default='Singleton', max_length=20, verbose_name='Forma de serialização'),
        ),
    ]
