# Generated by Django 2.2.2 on 2019-08-08 22:57

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20190808_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='temadado',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
