# Generated by Django 2.2.2 on 2019-08-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_temadado_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dado',
            old_name='data_type_new',
            new_name='data_type',
        ),
        migrations.RemoveField(
            model_name='dado',
            name='data_type_old',
        ),
    ]
