# Generated by Django 2.2.4 on 2019-08-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20190809_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icone',
            options={'verbose_name': 'ícone'},
        ),
        migrations.AlterModelOptions(
            name='temadado',
            options={'verbose_name': 'tema de dados', 'verbose_name_plural': 'temas de dados'},
        ),
        migrations.AlterModelOptions(
            name='tipodado',
            options={'verbose_name': 'tipo de dados', 'verbose_name_plural': 'tipos de dados'},
        ),
        migrations.AlterField(
            model_name='dado',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_by_type', to='api.TipoDado', verbose_name='tipo da caixinha'),
        ),
    ]
