# Generated by Django 2.2.4 on 2019-09-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprj_plus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icone',
            name='image_data',
        ),
        migrations.AlterField(
            model_name='icone',
            name='image',
            field=models.ImageField(upload_to='icones/mprj_plus/'),
        ),
    ]
