# Generated by Django 2.2.4 on 2019-09-20 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icones', '0001_initial'),
        ('mprj_plus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='icone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='icones.Icone'),
            preserve_default=False,
        ),
    ]
