# Generated by Django 2.2.4 on 2019-09-17 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mprj_plus', '0002_auto_20190917_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='icone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lupa.Icone'),
        ),
        migrations.DeleteModel(
            name='Icone',
        ),
    ]
