from decouple import config


DESAPARECIDOS_DB_USER = config('DESAPARECIDOS_DB_USER')
DESAPARECIDOS_DB_PWD = config('DESAPARECIDOS_DB_PWD')
DESAPARECIDOS_DB_HOST = config('DESAPARECIDOS_DB_HOST')
DESAPARECIDOS_DATA_LEN = config('DESAPARECIDOS_DATA_LEN', cast=int)
DESAPARECIDOS_CACHE_TIMEOUT = config(
    'DESAPARECIDOS_CACHE_TIMEOUT',
    cast=int,
    default=86400
)
