# Generated by Django 2.2.7 on 2020-02-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctoClasse',
            fields=[
                ('cldc_dk', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='cldc_ds_classe', max_length=150)),
            ],
            options={
                'db_table': 'MCPR_CLASSE_DOCTO_MP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('docu_dk', models.IntegerField(primary_key=True, serialize=False)),
                ('num_mp', models.CharField(db_column='docu_nr_mp', max_length=15)),
            ],
            options={
                'db_table': 'MCPR_DOCUMENTO',
                'managed': False,
            },
        ),
    ]
