# Generated by Django 2.2.2 on 2020-06-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominio', '0002_andamento_orgao_pessoafisica_subandamento_usuario_vista'),
    ]

    operations = [
        migrations.CreateModel(
            name='RHFuncionario',
            fields=[
                ('cdmatricula', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'RH_FUNCIONARIO',
                'managed': False,
            },
        ),
    ]
